### ISSUE TITLE
checkIsMultiple function

### ISSUE THREAD

**Issue by yactouat** [yactouat/yac-math#12]

**Comment by petropok** [comment]
Hello, do you accept contributions? and if so, can i work on this function?

**Comment by yactouat** [comment]
> Hello! do you accept contributions? and if so, can i work on this function

Hey @petropok , thanks for asking ! of course I do I'd be happy to :)

This library is quite new, so my only contributions guidelines are: "test what's coded" using the `jest` library (you'll find tests at `index.test.js` to give you some inspiration if you're not comfortable with `jest`.

To contribute, all you need to do is fork the repo and create a pull request when you're ready :)

**Comment by petropok** [comment]
thats great! :D
