### ISSUE TITLE
add a method for factorials

### ISSUE THREAD

**Issue by yactouat** [yactouat/yac-math#43]

**Comment by dejanko25** [comment]
Hello,
I have successfully created the function for calculating factorial of a number and added multiple tests using jest-theories to prove my implementation.
I will send a pull-request shortly, I would appreciate if you looked at it! :)

**Comment by yactouat** [comment]
hey @dejanko25 thank you very much for tackling this one, will be happy to see your PR !

**Comment by dejanko25** [comment]
Please correct me on anything, I think this should be resolved by #55

**Comment by yactouat** [comment]
merged !
