### ISSUE TITLE
leave formatting out of the implementation in `getDecimalToHoursAndMinutes`

### ISSUE THREAD

**Issue by yactouat** [yactouat/yac-math#47]

**Comment by dejanko25** [comment]
What other format would you like me to implement in this method? I have checked what the current one is.

**Comment by yactouat** [comment]
@dejanko25 , while answering your question, I figured "why not decouple the output string from the logic the function implements and let the implementor choose how to display that output", hence => https://github.com/yactouat/yac-math/pull/56
